'use client';

import type { Metadata } from "next";
import localFont from "next/font/local";
import Script from 'next/script';
import "./globals.css";
import { FontProvider } from './context/FontContext';
import { LanguageProvider } from './context/LanguageContext'; // Ensure LanguageProvider is imported
import FontWrapper from './components/FontWrapper'; // Ensure FontWrapper is imported

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});
const aakai = localFont({
    src: "./fonts/aaKaiTi_website_text.woff",
    variable: "--font-aakai",
    weight: "100 900",
});
const aakaiSong = localFont({
    src: "./fonts/aaKaiSong_website_text.woff",
    variable: "--font-aakaiSong",
    weight: "100 900",
});
const lxgw = localFont({
    src: "./fonts/lxgw_website_text.woff",
    variable: "--font-lxgw",
    weight: "100 900",
});
const hyfs = localFont({
    src: "./fonts/hyFangSong_website_text.woff",
    variable: "--font-hyfs",
    weight: "200 1000",
});
const qnlb = localFont({
    src: "./fonts/qnBianLi_website_text.woff",
    variable: "--font-qnlb",
    weight: "100 900",
});
const rzykt = localFont({
    src: "./fonts/rzyKaiTi_website_text.woff",
    variable: "--font-rzykt",
    weight: "100 900",
});
const twzk = localFont({
    src: "./fonts/twZhengKai_website_text.woff",
    variable: "--font-twzk",
    weight: "100 900",
});
const wqwh = localFont({
    src: "./fonts/wqwMiHei_website_text.woff",
    variable: "--font-wqwh",
    weight: "100 900",
});

/* export const metadata: Metadata = {
  title: "乾隆大藏经",
  description: "Generated by create next app",
};
 */

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="convertible">
      <body className={`antialiased ${geistSans.variable} ${geistMono.variable} ${aakai.variable} ${aakaiSong.variable} ${lxgw.variable} ${hyfs.variable} ${qnlb.variable} ${rzykt.variable} ${twzk.variable} ${wqwh.variable}`}>
        <Script src="https://cdn.jsdelivr.net/npm/opencc-js@1.0.5/dist/umd/full.min.js" strategy="beforeInteractive" />
        <FontProvider>
          <LanguageProvider>
            <FontWrapper>
              {children}
            </FontWrapper>
          </LanguageProvider>
        </FontProvider>
      </body>
    </html>
  );
}
